language: node_js
node_js:
  - 10
services:
  - docker
env:
  global:
    - PACT_BROKER_BASE_URL=https://oracle-naga.pactflow.io
    - PACT_BROKER_PUBLISH_VERIFICATION_RESULTS=true
    # Encrypted PACT_BROKER_TOKEN
    - secure: "ZXqIhMyvlghXc4JMR/n+peZGSNfC6pM8nozBu0v6O5r/upiBw0iL1KV4oredA2eE1rai88UXTUum/i8aMUYzbjWFSYH0i3WL4uJHwpbglcS8BbENIXT/oP5KkAn8hAUMWlaxr9FsJ3ko+xJ5ZILZsit1Q/c+e3Cuvc2ZYGzXZGbrdy2QfpRMxwNDXzzNWHYrqc3edns3eymHYsWmR/VBVKqqOroiXGSOEqvtTPVLDrl92E5QvUEcvtYZvs0xNw5AzGlBhuvr4u+1gTDneWe9DDjvU6yFALCpQODJ9wITV/RtNGOq3VYC33EyjjzzJRzWOFfMjm+7/JqvNFlXf7XMKfJslFDLjFW6If3d0VxwKNcuFIJInyOplM/0Xu/FALuHZl3ysbhM2EADvgKlc48fdOetre2H9FRCQMFdh1ACGEcJlmM087M8UNeHRbZc5cdveZyPkgR0t8q/mf7useXGnVQGxtx/PtyqgrvN8Ph6OjZwXBqH4mBN+lIfAuP8WM/qVEHk92fTHiLlUDogE89xb0cuKpCISxNjPntBPknwKN3q9CaI09juPYeXFS3Q+oxsh6Tj8mQlU4n7oCR/u8AwecBtedZpu2gFBm0W8ydzPmuGnlAOD7Id98GpNVSG+w9MEx6pslI9wxZN+5+Vf1z2+uYMmYRD6j+076uvqZQViLc="
before_script:
  - docker pull pactfoundation/pact-cli:latest
script:
  # When a webhook triggers a build, the PACT_URL will be set. In this case, just run the verification step.
  # Otherwise, run the normal build.
  # This is just to get around the fact that Travis CI only has one build definition per repository.
  # Normally you would define a separate job for the webhook triggered verification.
  - >
    if [ -n "${PACT_URL}" ]; then
      make ci_webhook
    else
      make ci
    fi
